[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/v1/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
DATABASE_URL = "postgresql://postgres:yPHavvxcXnHQzwrXQtrEqMcraqyzQETf@tramway.proxy.rlwy.net:59578/railway"
DB_HOST = "tramway.proxy.rlwy.net"
DB_PORT = "59578"
DB_NAME = "railway"
DB_USERNAME = "postgres"
DB_PASSWORD = "yPHavvxcXnHQzwrXQtrEqMcraqyzQETf"
SPRING_PROFILES_ACTIVE = "railway"
JWT_SECRET = "c2VhYW5kdGVhLXByb2R1Y3Rpb24tanNlY3JldC1rZXktMjAyNC1yYWlsd2F5LWRlcGxveW1lbnQ="
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
STRIPE_SECRET_KEY = ""
STRIPE_PUBLISHABLE_KEY = ""
STRIPE_WEBHOOK_SECRET = ""
AWS_ACCESS_KEY = ""
AWS_SECRET_KEY = ""
AWS_S3_BUCKET = "seaandtea-uploads"
AWS_REGION = "us-east-1"


